name: rikka
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  logging: ^1.0.2
  onebot:
    path: ../../../onebot
  toml: ^0.12.0

dev_dependencies:
  lints: ^1.0.0
